# Generated by Django 2.2.24 on 2022-02-04 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('num_of_rsvp', models.IntegerField()),
                ('flag_attending', models.CharField(max_length=1)),
                ('message_body', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
